# Generated by Django 4.2.7 on 2023-11-02 12:32

from django.db import migrations, models
import marksheet.models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(validators=[marksheet.models.unique_roll_no_validator]),
        ),
    ]
